version: 4
jobs:
  validate_test:
    template: python/validate_unittest
    secrets:
      - CODECOV_TOKEN
    requires: [~commit, ~pr]

  validate_lint:
    template: python/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python/validate_codestyle
    requires: [~commit, ~pr]

  generate_version:
    template: python/generate_version
    requires: [~commit]
    
  package_python_sdist:
    template: python/package_python_sdist
    requires: [validate_test, validate_lint, validate_codestyle, generate_version]
