version: 4

jobs:
  validate_test:
    template: python/validate_unittest
    secrets:
      - CODECOV_TOKEN
    steps:
      - postinstall_tox: $BASE_PYTHON -m pip install codecov coverage
      - postvalidate_code: |
          coverage combine
          codecov
    requires: [~commit, ~pr]

  validate_lint:
    template: python/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python/validate_codestyle
    requires: [~commit, ~pr]

  package_python_sdist:
    template: python/package_python_sdist
    requires: [validate_test, validate_lint, validate_codestyle]

